### ISSUE TITLE
src\scss\common.scss'withCtx' is imported from external module 'vue' but never used

### ISSUE THREAD

**Issue by SystemDZ** [damowangzhu/Vite2-Vue3-SSR-TS-Vuex-VueRouter#1]
![image](https://user-images.githubusercontent.com/5507558/114141194-42c0e980-98df-11eb-844b-c3d0ff3245c0.png)

after running npm run preview and importing @common.scss

**Comment by damowangzhu** [comment]
// app.vue 
<style scoped>...</style>  
    => 
 <style> ...  </style>
